### ISSUE TITLE
KeyError warc-target-uri

### ISSUE THREAD

**Issue by vschiavoni** [internetarchive/warc#19]
I get this:

`````` python
~$ python warcread.py 
<warc.warc.WARCFile instance at 0x7fc61fc34290>
Traceback (most recent call last):
  File "warcread.py", line 6, in <module>
    print(record['WARC-Target-URI'])
  File "/usr/local/lib/python2.7/dist-packages/warc/warc.py", line 199, in __getitem__
    return self.header[name]
  File "/usr/local/lib/python2.7/dist-packages/warc/utils.py", line 34, in __getitem__
    return self._d[name.lower()]
KeyError: 'warc-target-uri'
```python

Input file can be downloaded from here (191 MB): 
https://www.dropbox.com/s/25tk1mpo03g73pj/1009wb-39.warc.gz?dl=0
``````

**Comment by Gijs-Koot** [comment]
Hi, the problem is that there is an error in the documentation I believe;

```
  print(record['WARC-Target-URI'])
```

doesn't work, but you should use

```
 print(record.header['WARC-Target-URI'])
```

I came here to suggest a fix, but this library is not maintained I think, judging from the commits.

**Comment by Segerberg** [comment]
My temporary workaround: 
``import warc
f = warc.open("file.warc.gz", "rb")

for record in f:
    if record['Warc-type'] == 'warcinfo':
        pass
    else:
        print record['Warc-type'],':', record['warc-target-uri']

``

**Comment by Segerberg** [comment]
My temporary workaround:

```
import warc
f = warc.open("file.warc.gz", "rb")

for record in f:
    if record['Warc-type'] == 'warcinfo':
        pass
    else:
        print record['Warc-type'],':', record['warc-target-uri']



```

**Comment by girishmt4** [comment]
> Hi, the problem is that there is an error in the documentation I believe;
> 
> ```
>   print(record['WARC-Target-URI'])
> ```
> doesn't work, but you should use
> 
> ```
>  print(record.header['WARC-Target-URI'])
> ```
> I came here to suggest a fix, but this library is not maintained I think, judging from the commits.

Actually it's 
record.header.get('WARC-Target-URI')
