### ISSUE TITLE
Bug in WARCRecord.__repr__()

### ISSUE THREAD

**Issue by petri** [internetarchive/warc#3]
The line in **repr**:

return "<WARCRecord: type=%r record_id=%s>" % (self['type'], self['record_id'])

results in an error. I don't know if the above line is wrong or whether there's a bug in how the attribute lookup chain is supposed to work. Changing the above line to this works though:

return "<WARCRecord: type=%r record_id=%s>" % (self.header.type, self.header.record_id)

Traceback below.

---

> > > h=WARCHeader({"WARC-Type": "response"}, defaults=True)
> > > r = WARCRecord(h)
> > > r
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "**init**.py", line 186, in **repr**
> > >     return "<WARCRecord: type=%r record_id=%s>" % (self['type'], self['record_id'])
> > >   File "**init**.py", line 172, in **getitem**
> > >     return self.header[name]
> > >   File "**init**.py", line 40, in **getitem**
> > >     return self._d[name.lower()]
> > > KeyError: 'type'

**Comment by petri** [comment]
Fix & test in https://github.com/koodaamo/warc/commit/c7b716557ca95b528dd2eb157102c9e321fc2cbc
