### ISSUE TITLE
Unsupported WARC version: 1.1

### ISSUE THREAD

**Issue by kiska3** [internetarchive/warc#34]
[example file](https://kiska.b-cdn.net/omESX/example.warc.gz)
```python
f = warc.open("example.warc.gz")
for record in f:
     print record['WARC-Target-URI'], record['Content-Length']
```
### Expected Behaviour
Prints records with URI + Content Length

### Observed Behaviour:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kiska/.local/lib/python2.7/site-packages/warc/warc.py", line 390, in __iter__
    record = self.read_record()
  File "/home/kiska/.local/lib/python2.7/site-packages/warc/warc.py", line 373, in read_record
    header = self.read_header(fileobj)
  File "/home/kiska/.local/lib/python2.7/site-packages/warc/warc.py", line 334, in read_header
    raise IOError("Unsupported WARC version: %s" % version)
IOError: Unsupported WARC version: 1.1

**Comment by ivanistheone** [comment]
This seems to be a known issue for `.warc.gz` files.

See workaround in https://github.com/internetarchive/warc/issues/21#issuecomment-200330407 and https://github.com/internetarchive/warc/issues/21#issuecomment-254750043 .

**Comment by JustAnotherArchivist** [comment]
@ivanistheone Yes, there are many bugs in this library. This is a lack of support for the WARC/1.1 specification though and has nothing to do with #21.
